//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/Scripts/CastleInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @CastleInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CastleInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CastleInput"",
    ""maps"": [
        {
            ""name"": ""InGameAction"",
            ""id"": ""39876a63-80ed-4384-b2fa-d3bdaf901f4b"",
            ""actions"": [
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""ba6ecf8b-d1ef-42dc-8f80-6133ef8b2523"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""4017f6fd-c85c-4b09-aecc-d76f74a025b1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""74196245-a6d2-4ff9-a39b-930ba4e8e68d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfac707b-5124-4d19-bc18-56b7b5df1f4b"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGameAction
        m_InGameAction = asset.FindActionMap("InGameAction", throwIfNotFound: true);
        m_InGameAction_Click = m_InGameAction.FindAction("Click", throwIfNotFound: true);
        m_InGameAction_MousePosition = m_InGameAction.FindAction("MousePosition", throwIfNotFound: true);
    }

    ~@CastleInput()
    {
        Debug.Assert(!m_InGameAction.enabled, "This will cause a leak and performance issues, CastleInput.InGameAction.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGameAction
    private readonly InputActionMap m_InGameAction;
    private List<IInGameActionActions> m_InGameActionActionsCallbackInterfaces = new List<IInGameActionActions>();
    private readonly InputAction m_InGameAction_Click;
    private readonly InputAction m_InGameAction_MousePosition;
    public struct InGameActionActions
    {
        private @CastleInput m_Wrapper;
        public InGameActionActions(@CastleInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Click => m_Wrapper.m_InGameAction_Click;
        public InputAction @MousePosition => m_Wrapper.m_InGameAction_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_InGameAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActionActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActionActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionActionsCallbackInterfaces.Add(instance);
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
        }

        private void UnregisterCallbacks(IInGameActionActions instance)
        {
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
        }

        public void RemoveCallbacks(IInGameActionActions instance)
        {
            if (m_Wrapper.m_InGameActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActionActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActionActions @InGameAction => new InGameActionActions(this);
    public interface IInGameActionActions
    {
        void OnClick(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
